services:
  downloader:
    build: .
    container_name: downloader
    ports:
      - "5000:5000"
    volumes:
      - /mnt/media/music:/music
      - ./cookies.txt:/app/cookies.txt
    restart: unless-stopped
